FORMAT: 1A
HOST: https://localhost

# NF-e

Integração com dados da SEFAZ com foco na Nota Fiscal Eletrônica.

## NF-e Criar [/nfe/criar/{ambiente}/{certId}]
### Criação das NF-e  [POST]
* Para a criação das NF-E será preciso dos seguintes campos
+ Request (application/json)
    + Attributes
        + nNF: 1050 (string, required)
        + xNome: Batman (string, required)
        + CEP: 70330545 (string, required)
        + xLgr: CLS 102 Bloco D (string, required)
        + xCpl: Apt 645 (string, required)
        + xBairro: Asa Sul (string, required)
        + xMun: Brasília (string, required)
        + nro: 30 (string, required)
        + UF: DF (string, required)
        + cpfCnpj: 487.851.370-57 / 73.768.627/0001-60 (string, required)
        + natOp: Descricao da venda (string, required)
        + xProd: Artigos para festa (string, required)
        + qCom:  2 (number, required)
        + qTrib: 2 (number, required)
        + vUnCom:  150 (number, required)
        + vUnTrib: 150 (number, required)
        + UF: DF (string, required)

+ Response 200 (application/json)

        {
            "message": "criado com sucesso"
        }

+ Response 400 (application/json)

        {
            "message": "This XML is not valid. Element '{http://www.portalfiscal.inf.br/nfe}': This element is not expected. Expected is ( {http://www.portalfiscal.inf.br/nfe} )."
        }

## NF-e Busca Dados [/nfe/buscar-notas/{id}]
### Retorna os dados da NF-e  [GET]

Retorna todos os dados da NF-E.

* Para o retorno dos dados da NF-E será preciso do _id.

+ Request 200 (application/json)
    + Attributes
        + id: 5caf8125d75b6a00075c1d40 (string, required)

+ Response 200 (application/json)

        {
            "message": "sucesso"
        }

+ Response 400 (application/json)

        {
            "message": "não foi possivel localizar a NF-E!"
        }

## NF-e Listar [/nfe/listar-notas/{usuario}]
### Lista todas NF-e  [GET]

Retorna lista de todas as NF-Es.

+ Response 200 (application/json)

            {
                "data": {
                        "attributes": {
                            "versao": "4.00"
                        },
                    },
                    "NFe": {
                        "infNFe": {
                            "attributes": {
                                "Id": "NFe53190532944459000130550010000006331139967538",
                              "versao": "4.00"
                            },
                         },
                   }
           }

+ Response 400 (application/json)

        {
            "message": "Dados não encontrados"
        }

## NF-e Download xml [/nfe/download-local/{chNfe}]
### Download do XML [GET]
* Para o download do arquivo xml da NF-E será preciso do número chNfe.

+ Request 200 (application/json)
    + Attributes
        + Id: 53190532944459000130550010000009021292641210 (string, required)
+ Response 200 (application/json)

        {
              "message": "Download com sucesso"
        }

+ Response 400 (application/json)

        {
              "message": "não foi possivel localizar a NF-E!"
        }

## NF-e Distribuição [/nfe/distribuicao/{ambiente}/{certId}]
Distribuição das NF-e em lote
### Distribuição das NF-e [GET]
+ Parameters
    + ambiente (string)
    + certId (string)
+ Request
    + Parameters
        + ambiente (string, required)
        + certId (string, required)
+ Response 200 (application/json)

        { "data":
            {"message":"Criado com Sucesso!"}
        }

+ Response 400 (application/json)

        {
            "error":{
                "message": "Notas não puderam ser recuperadas!"
            }
        }

## NF-e Consultar Recibo [/nfe/consultar-recibo/{recibo}/{ambiente}]
### Consultar Recibo Nota Fiscal [GET]

Consultar recibo da NF-E.

* Para a geração da NF-E será preciso do cnpj e da inscrição estadual

+ Request 200 (application/json)
    + Attributes
        + recibo: 533002185307626 (string, required)
+ Response 200 (application/json)

        {
              "message": "Salvo com sucesso"
        }

+ Response 400 (application/json)

        {
            "message": "rejeitada"
        }


## Certificado Cadastrar [/admin/cadastrar-certificado]
### Cadastro dos Certificados [POST]

Cadastrar Certificados


* Para a geração da NF-E será preciso do cnpj e da inscrição estadual

+ Request 200 (application/json)
    + Attributes
        + razaosocial: Nome teste (string, required)
        + cnpj: 20.190.686/0001-38 (string, required)
        + tpAmb: 1/2 (string, required)
        + pass: senha (string, required)
        + path: caminho (string, required)
+ Response 200 (application/json)

         { "data":
                    {"message":"Criado com Sucesso!"}
                }

+ Response 400 (application/json)

        {
            "message": "Error"
        }

## Certificado Listar [/admin/listar-certificado]
Listar Certificados
### Listagem dos Certificados [GET]
+ Response 200 (application/json)

        { "data":
            {"message":"Criado com Sucesso!"}
        }

+ Response 400 (application/json)

        {
            "error":{
                "message": "Error"
            }
        }
