FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# NF-E

Integração com dados da sefaz com foco na Nota Fiscal Eletrônica.

## NF-E [/nfe?codigo={codigo}]

### Consultar Nota Fiscal com Codigo de Acesso [GET]

Codigo é necessario codigo de acesso de 44 caracteres para retorna dados da NFE.
+ Parameters
    + codigo (string) 
        
+ Request
    + Parameters
        + codigo (string, required) 
        
+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }

+ Response 400 (application/json)

        {
            "erro": "nota fiscal eletronica não encontrada!"
        }

### Salvar dados NFE [POST]

Gera e salva os dados da NF-E.

+ Request 200 (application/json)
    + Attributes 
        + cnpj: 111.111.11/0001-98 (string, required)

+ Response 200 (application/json)

        {
              "message": "Salvo com sucesso"
        }
        
+ Response 400 (application/json)

        {
            "message": "não foi possivel gerar a NF-E!"
        }


## VALIDAR NFE [/validar-nfe]
### Validar Nota Fiscal [GET]

Verifica junto a Sefaz a validade da NFE.

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }
        

## Extrair NF-E [/extrair-nfe]
### Extrai  Nota Fiscal [GET]

Recebe todas as notas fiscais do cnpj.

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }
        
        
## Download NF-E [/download-nfe/{codigoAcesso}/{ambiente}]
### Download  Nota Fiscal [GET]

Download da NF-E.

* O Emitente da nota não pode fazer o download da nota.

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }

+ Response 400 (application/json)
        
        {
           "attributes":{
              "versao":"1.01"
           },
           "tpAmb":"2",
           "verAplic":"1.1.9",
           "cStat":"641",
           "xMotivo":"Rejeicao: NF-e indisponivel para o emitente",
           "dhResp":"2019-03-25T09:40:30-03:00"
        }

## Importar NF-E [/importar-nfe]
### Importar  Nota Fiscal [GET]

recebe uma nota por download.

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }