FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# NF-E

Integração com dados da sefaz com foco na Nota Fiscal Eletrônica.

## NF-E [/nfe?codigo={codigo}]

### Consultar Nota Fiscal com Codigo de Acesso [GET]

Codigo é necessario codigo de acesso de 44 caracteres para retorna dados da NFE.
+ Parameters
    + codigo (string)

+ Request
    + Parameters
        + codigo (string, required)

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }

+ Response 400 (application/json)

        {
            "erro": "nota fiscal eletronica não encontrada!"
        }

### Salvar dados NFE [POST]

Gera e salva os dados da NF-E.

+ Request 200 (application/json)
    + Attributes
        + cnpj: 111.111.11/0001-98 (string, required)

+ Response 200 (application/json)

        {
              "message": "Salvo com sucesso"
        }

+ Response 400 (application/json)

        {
            "message": "não foi possivel gerar a NF-E!"
        }


## VALIDAR NFE [/validar-nfe]
### Validar Nota Fiscal [GET]

Verifica junto a Sefaz a validade da NFE.

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }


## Extrair NF-E [/extrair-nfe]
### Extrai  Nota Fiscal [GET]

Recebe todas as notas fiscais do cnpj.

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }


## Download NF-E [/download-nfe/{codigoAcesso}/{ambiente}]
### Download  Nota Fiscal [GET]

Download da NF-E.

* O Emitente da nota não pode fazer o download da nota.

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }

+ Response 400 (application/json)

        {
           "attributes":{
              "versao":"1.01"
           },
           "tpAmb":"2",
           "verAplic":"1.1.9",
           "cStat":"641",
           "xMotivo":"Rejeicao: NF-e indisponivel para o emitente",
           "dhResp":"2019-03-25T09:40:30-03:00"
        }

## Importar NF-E [/importar-nfe]
### Importar  Nota Fiscal [GET]

recebe uma nota por download.

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }

## Gerar NF-E [/gerar-nfe/{ambiente}]
### Geração Nota Fiscal [POST]

Geração da NF-E.

* Para a geração da NF-E será preciso do cnpj e da inscrição estadual

+ Request 200 (application/json)
    + Attributes
        + nNF: 12 (string, required)
        + CNPJ: 111.111.11/0001-98 (string, required)
        + IE: 0000366100100 (string, required)
+ Response 200 (application/json)

        {
              "message": "Salvo com sucesso"
        }

+ Response 400 (application/json)

        {
            "message": "não foi possivel gerar a NF-E!"
        }

## Consultar Recibo [/consultar-recibo/{recibo}]
### Consultar Recibo Nota Fiscal [GET]

Consultar recibo da NF-E.

* Para a geração da NF-E será preciso do cnpj e da inscrição estadual

+ Request 200 (application/json)
    + Attributes
        + recibo: 533002185307626 (string, required)
+ Response 200 (application/json)

        {
              "message": "Salvo com sucesso"
        }

+ Response 400 (application/json)

        {
            "message": "rejeitada"
        }

## Listar NFE [/listar-notas]
### Lista todas NFE  [GET]

Retorna lista de todas as NF-Es.

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }

+ Response 400 (application/json)

        {
            "message": "não foi possivel localizar a NF-E!"
        }

## Busca Dados da NFE [/buscar-notas/{id}]
### Retorna os dados da NFE  [GET]

Retorna todos os dados da NF-E.

* Para o retorno dos dados da NF-E será preciso do _id
+ Request 200 (application/json)
    + Attributes
        + id: 5caf8125d75b6a00075c1d40 (string, required)
+ Response 200 (application/json)

        {
              "message": "sucesso"
        }
+ Response 400 (application/json)

        {
            "message": "não foi possivel localizar a NF-E!"
        }

## Criar NFE [/criar-nfe/{ambiente}]
### Criação das NFE  [POST]

* Para a criação das NF-E será preciso dos seguintes campos
    + Request 200 (application/json)
        + Attributes
            + xNF: 1050 (string, required)
            + xNome: Batman (string, required)
            + CEP: 70330545 (string, required)
            + xLgr: CLS 102 Bloco D (string, required)
            + xCpl: Apt 645 (string, required)
            + xBairro: Asa Sul (string, required)
            + xMun: Brasília (string, required)
            + nro: 30 (string, required)
            + UF: DF (string, required)
            + CPF: 75512793004 (string, required)
            + natOp: Descricao da venda (string, required)
            + xProd: Artigos para festa (string, required)
            + qCom:  2 (number, required)
            + qTrib: 2 (number, required)
            + vUnCom:  150 (number, required)
            + vUnTrib: 150 (number, required)
            + UF: DF (string, required)

+ Response 200 (application/json)

        {
            "message": "sucesso"
        }
+ Response 400 (application/json)

        {
            "message": "This XML is not valid. Element '{http://www.portalfiscal.inf.br/nfe}': This element is not expected. Expected is ( {http://www.portalfiscal.inf.br/nfe} )."
        }