FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# nfe

Polls is a simple API allowing consumers to view polls and vote in them.

## NFE [/nfe]

### Consultar Nota Fiscal com Codigo de Acesso [GET]

Codigo é necessario codigo de acesso de 44 caracteres para retorna dados da NFE.

+ Response 200 (application/json)


        {
            "codigo": "12340623004804000164550000000002251000002258"
        }

### Salvar dados NFE [POST]

Salvar dados da NFE.

+ Response 200 (application/json)


        {
            "codigo": "12340623004804000164550000000002251000002258"
        }


## VALIDAR NFE [/validar-nfe]
### Validar Nota Fiscal [GET]

Verifica junto a Sefaz a validade da NFE.

+ Response 200 (application/json)

        {
            "codigo": "12340623004804000164550000000002251000002258"
        }

